# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 778abf0316a2672cf42a9635866a31c8b002610134098f3d7b0b72cd0461126c49b13895e7f15dcbc4b7f7c9dae31423b92d22ceeaf95b0c3664d45c9f0df029

test:
  secret_key_base: 636250579781f26403e3e208769b08fa539189b4180c05783d1484ca1e5ba520e6796c1ae66105d1f18b77e90c071e7841b53352e3f8becf4a48a75baf68c0cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
